#include <cpu/opcodes.h>
#include <cpu/memory.h>

#include <stdio.h>

/*
    addr8 = 8-bit address of I/O port
    reg8 = AL = 0, CL = 1, DL = 2, BL = 3, AH =4, CH = 5, DH = 6, BH = 7
    reg16 = AX = 0, CX =1, DX =2, BX =3, SP = 4, BP = 5, SI = 6, DI = 7
    sreg = ES = 0, CS = 1, SS = 2, DS = 3
    mem8 = memory byte (direct addressing only)
    mem16 = memory word (direct addressing only)
    r/m8 = reg8 or mem8
    r/m16 = reg16 or mem16
    imm8 = 8 bit immediate
    imm16 = 16 bit immediate
 */

const struct opcode opcodes[256] = {
        {"ADD r/m8, r8", 2, NULL},
        {"ADD r/m16, r16", 3, NULL},
        {"ADD r8, r/m8", 2, NULL},
        {"ADD r16, r/m16", 3, NULL},
        {"ADD al, imm8", 1, NULL},
        {"ADD ax, imm16", 3, NULL},
        {"PUSH es", 0, NULL},
        {"POP es", 0, NULL},
        {"OR r/m8, r8", 2, NULL},
        {"OR r/m16, r16", 3, NULL},
        {"OR r8, r/m8", 2, NULL},
        {"OR r16, r/m16", 3, NULL},
        {"OR al, imm8", 1, NULL},
        {"OR ax, imm16", 3, NULL},
        {"PUSH cs", 0, NULL},
        {"POP cs", 0, NULL},
        {"ADC r/m8, r8", 2, NULL},
        {"ADC r/m16, r16", 3, NULL},
        {"ADC r8, r/m8", 2, NULL},
        {"ADC r16, r/m16", 3, NULL},
        {"ADC al, imm8", 1, NULL},
        {"ADC ax, imm16", 2, NULL},
        {"PUSH ss", 0, NULL},
        {"POP ss", 0, NULL},
        {"SBB r/m8, r8", 2, NULL},
        {"SBB r/m16, r16", 3, NULL},
        {"SBB r8, r/m8", 2, NULL},
        {"SBB r16, r/m16", 3, NULL},
        {"SBB al, imm8", 1, NULL},
        {"SBB ax, imm8", 1, NULL},
        {"PUSH ds", 0, NULL},
        {"POP ds", 0, NULL},
        {"AND r/m8, r8", 2, NULL},
        {"AND r/m16, r16", 3, NULL},
        {"AND r8, r/m8", 2, NULL},
        {"AND r16, r/m16", 3, NULL},
        {"AND al, imm8", 1, NULL},
        {"AND ax, imm16", 2, NULL},
        {"DAA", 0, NULL},
        {"SUB r/m8, r8", 2, NULL},
        {"SUB r/m16, r16", 3, NULL},
        {"SUB r8, r/m8", 2, NULL},
        {"SUB r16, r/m16", 3, NULL},
        {"SUB al, imm8", 1, NULL},
        {"SUB ax, imm16", 2, NULL},
        {"", 0, NULL},
        {"DAS", 0, NULL},
        {"XOR r/m8, r8", 2, NULL},
        {"XOR r/m16, r16", 3, NULL},
        {"XOR r8, r/m8", 2, NULL},
        {"XOR r16, r/m16", 3, NULL},
        {"XOR al, imm8", 1, NULL},
        {"XOR ax, imm16", 2, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"AAA", 0, NULL},
        {"CMP r/m8, r8", 2, NULL},
        {"CMP r/m16, r16", 3, NULL},
        {"CMP r8, r/m8", 2, NULL},
        {"CMP r16, r/m16", 3, NULL},
        {"CMP al, imm8", 1, NULL},
        {"CMP ax, imm16", 2, NULL},
        {"", 0, NULL},
        {"AAS", 0, NULL},
        {"INC ax", 0, NULL},
        {"INC cx", 0, NULL},
        {"INC dx", 0, NULL},
        {"INC bx", 0, NULL},
        {"INC sp", 0, NULL},
        {"INC bp", 0, NULL},
        {"INC si", 0, NULL},
        {"INC di", 0, NULL},
        {"DEC ax", 0, NULL},
        {"DEC cx", 0, NULL},
        {"DEC dx", 0, NULL},
        {"DEC bx", 0, NULL},
        {"DEC sp", 0, NULL},
        {"DEC bp", 0, NULL},
        {"DEC si", 0, NULL},
        {"DEC di", 0, NULL},
        {"PUSH ax", 0, NULL},
        {"PUSH cx", 0, NULL},
        {"PUSH dx", 0, NULL},
        {"PUSH bx", 0, NULL},
        {"PUSH sp", 0, NULL},
        {"PUSH bp", 0, NULL},
        {"PUSH si", 0, NULL},
        {"PUSH di", 0, NULL},
        {"POP ax", 0, NULL},
        {"POP cx", 0, NULL},
        {"POP dx", 0, NULL},
        {"POP bx", 0, NULL},
        {"POP sp", 0, NULL},
        {"POP bp", 0, NULL},
        {"POP si", 0, NULL},
        {"POP di", 0, NULL},
        {"PUSHA", 0, NULL},
        {"POPA", 0, NULL},
        {"BOUND r16, m16", 3, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"PUSH imm16", 1, NULL},
        {"IMUL r16, r/m16, imm16", 4, NULL},
        {"PUSH imm8", 1, NULL},
        {"IMUL r16, r/m16, imm8", 3, NULL},
        {"INSB", 0, NULL},
        {"INSW", 0, NULL},
        {"OUTSB", 0, NULL},
        {"OUTSW", 0, NULL},
        {"JO rel8", 1, NULL},
        {"JNO rel8", 1, NULL},
        {"JB rel8", 1, NULL},
        {"JNB rel8", 1, NULL},
        {"JZ rel8", 1, NULL},
        {"JNZ rel8", 1, NULL},
        {"JBE rel8", 1, NULL},
        {"JA rel8", 1, NULL},
        {"JS rel8", 1, NULL},
        {"JNS rel8", 1, NULL},
        {"JPE rel8", 1, NULL},
        {"JPO rel8", 1, NULL},
        {"JL rel8", 1, NULL},
        {"JGE rel8", 1, NULL},
        {"JLE rel8", 1, NULL},
        {"JG rel8", 1, NULL},
        {"GRP1 r/m8, imm8", 2, NULL},
        {"GRP1 r/m16, imm8", 2, NULL},
        {"GRP1 r/m8, imm8", 2, NULL},
        {"GRP1 r/m16, imm8", 2, NULL},
        {"TEST r8, r/m8", 2, NULL},
        {"TEST r16, r/m16", 2, NULL},
        {"XCHG r8, r/m8", 2, NULL},
        {"XCHG r16, r/m16", 2, NULL},
        {"MOV r/m8, r8", 2, NULL},
        {"MOV r/m16, r16", 2, NULL},
        {"MOV r8, r/m8", 2, NULL},
        {"MOV r16, r/m16", 2, NULL},
        {"MOV r/m16, sreg", 2, NULL},
        {"LEA r16, mem16", 2, NULL},
        {"MOV sreg, r/m16", 2, NULL},
        {"POP r/m16", 1, NULL},
        {"NOP", 0, NULL},
        {"XCHG CX, AX", 0, NULL},
        {"XCHG DX, AX", 0, NULL},
        {"XCHG BX, AX", 0, NULL},
        {"XCHG SP, AX", 0, NULL},
        {"XCHG BP, AX", 0, NULL},
        {"XCHG SI, AX", 0, NULL},
        {"XCHG DI, AX", 0, NULL},
        {"CBW", 0, NULL},
        {"CWD", 0, NULL},
        {"CALL m16:16", 2, NULL},
        {"WAIT", 0, NULL},
        {"PUSHF", 0, NULL},
        {"POPF", 0, NULL},
        {"SAHF", 0, NULL},
        {"LAHF", 0, NULL},
        {"MOV al, moffs8", 1, NULL},
        {"MOV ax, moffs16", 1, NULL},
        {"MOV moffs8, al", 1, NULL},
        {"MOV moffs16, ax", 1, NULL},
        {"MOVSB", 0, NULL},
        {"MOVSW", 0, NULL},
        {"CMPSB", 0, NULL},
        {"CMPSW", 0, NULL},
        {"TEST al, imm8", 1, NULL},
        {"TEST ax, imm16", 2, NULL},
        {"STOSB", 0, NULL},
        {"STOSW", 0, NULL},
        {"LODSB", 0, NULL},
        {"LODSW", 0, NULL},
        {"SCASB", 0, NULL},
        {"SCASW", 0, NULL},
        {"MOV al, imm8", 1, NULL},
        {"MOV cl, imm8", 1, NULL},
        {"MOV dl, imm8", 1, NULL},
        {"MOV bl, imm8", 1, NULL},
        {"MOV ah, imm8", 1, NULL},
        {"MOV ch, imm8", 1, NULL},
        {"MOV dh, imm8", 1, NULL},
        {"MOV bh, imm8", 1, NULL},
        {"MOV ax, imm16", 2, NULL},
        {"MOV cx, imm16", 2, NULL},
        {"MOV dx, imm16", 2, NULL},
        {"MOV bx, imm16", 2, NULL},
        {"MOV sp, imm16", 2, NULL},
        {"MOV bp, imm16", 2, NULL},
        {"MOV si, imm16", 2, NULL},
        {"MOV di, imm16", 2, NULL},
        {"GRP2 r/m8, imm8", 1, NULL},
        {"GRP2 r/m16, imm8", 1, NULL},
        {"RET imm16", 2, NULL},
        {"RET", 0, NULL},
        {"LES r16, m16:16", 3, NULL},
        {"LDS r16, m16:16", 3, NULL},
        {"MOV r8, m8", 2, NULL},
        {"MOV r16, m16", 2, NULL},
        {"ENTER", 0, NULL},
        {"LEAVE", 0, NULL},
        {"RETF imm16", 2, NULL},
        {"RETF", 0, NULL},
        {"INT3", 0, NULL},
        {"INT imm8", 1, NULL},
        {"INTO", 0, NULL},
        {"IRET", 0, NULL},
        {"GRP2 r/m8, 1", 1, NULL},
        {"GRP2 r/m16, 1", 1, NULL},
        {"GRP2 r/m8, cl", 1, NULL},
        {"GRP2 r/m16, cl", 1, NULL},
        {"AAM imm8", 1, NULL},
        {"AAD imm8", 1, NULL},
        {"SALC", 0, NULL},
        {"XLAT", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"[x87ONLY]", 0, NULL},
        {"LOOPNZ rel8", 1, NULL},
        {"LOOPZ rel8", 1, NULL},
        {"LOOP rel8", 1, NULL},
        {"JCXZ rel8", 1, NULL},
        {"IN al, imm8", 1, NULL},
        {"IN ax, imm8", 1, NULL},
        {"OUT imm8, al", 1, NULL},
        {"OUT imm8, ax", 1, NULL},
        {"CALL rel16", 1, NULL},
        {"JMP rel16", 1, NULL},
        {"JMP m16:16", 1, NULL},
        {"JMP rel8", 1, NULL},
        {"IN al, dx", 0, NULL},
        {"IN ax, dx", 0, NULL},
        {"OUT dx, al", 0, NULL},
        {"OUT dx, ax", 0, NULL},
        {"LOCK", 0, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"", 0, NULL},
        {"HLT", 0, NULL},
        {"CMC", 0, NULL},
        {"GRP3a r/m8", 1, NULL},
        {"GRP3b r/m16", 1, NULL},
        {"CLC", 0, NULL},
        {"STC", 0, NULL},
        {"CLI", 0, NULL},
        {"STI", 0, NULL},
        {"CLD", 0, NULL},
        {"STD", 0, NULL},
        {"GRP4 r/m8", 0, NULL},
        {"GRP5 r/m16", 0, NULL},
};

void opcode_execute(struct cpu *cpu) {
    uint8_t opcode_byte = memory_read_byte(cpu, cpu->reg.ip32);
    struct opcode opcode = opcodes[opcode_byte];

    if (/* opcode.function == NULL */ 0) {
        printf("[!] Not implemented or invalid instruction %#x (%s) hit, bailing out.\n", opcode_byte, opcode.name);
        cpu->state |= CPU_HALTED;
    } else {
        printf("%s\nIP: %#x    CS: %#x\nIP32: %#x\n--------\n", opcode.name, cpu->reg.ip, cpu->reg.cs, cpu->reg.ip32);
    }

    if (opcode.operand_length) cpu->reg.ip += opcode.operand_length;
    else cpu->reg.ip++;

    // PhysicalAddress = Segment * 16 + Offset
    cpu->reg.ip32 = cpu->reg.cs * 16 + cpu->reg.ip;
}